version: "3"
services:
  api:
    build: .
    env_file: .env
    environment:
      - THANKSAPI_PORT=8080
    command: go run main.go
    volumes:
      - .:/go/src/github.com/lucasmagnum/thanks-api/
    ports:
      - "8080:8080"
